/* XPM */
static char *dynamite[] = {
/* width height ncolors chars_per_pixel */
"32 32 5 1",
/* colors */
"` c black",
"a c red",
"b c white",
"c c grey",
"d c yellow",
/* pixels */
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbb``bbdbbbbbabbbbbbbbbbbbb",
"bbbbbbb`bb`bbabbbbbbbbbbbbbbbbbb",
"bbbbbb`bbbb`bbdabbbbbbbbbbbbbbbb",
"bbbbbb`bbba`dbabbbbbbbbbbbbbbbbb",
"bbbbbb`bbadb`babbbbbbbbbbbbbbbbb",
"bbbbb`bbbbadd`bbbabbbbbbbbbbbbbb",
"bbbb`bbbbbabab`bbbbbbbbbbbbbbbbb",
"bbb`bbbbabbbbbb`bbbbbbbbbbbbbbbb",
"bbb`bbbbabbbbbbbbbbbbbbbbbbbbbbb",
"bbb`bbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbb``````````````````````````bbb",
"bbb`c`aaaa`db`aaaaaaa`db`aaaa`bb",
"bbb`c`aaaa`bd`aaaaaaa`bd`aaaa`bb",
"bb``````````bd`````````bd`````bb",
"bb`c`c`aaaa`db`aaaaaaa`db`aaaa`b",
"bb`c`c`aaaa`bd`aaaaaaa`bd`aaaa`b",
"bb`````````db`````````bd``````bb",
"bbb`c`aaaa`bd`aaaaaaa`db`aaaa`bb",
"bbb`c`aaaa`db`aaaaaaa`bd`aaaa`bb",
"bbbb`````````````````````````bbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
};
