/* XPM */
static char *fire_2.xpm_xpm[] = {
/* width height ncolors chars_per_pixel */
"32 32 4 1",
/* colors */
"` c black",
"a c red",
"b c white",
"c c yellow",
/* pixels */
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbb``bbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbb`c`bbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbb`c`bbbbbb`bbbbbbbb",
"bbbbbbbbbbbbbb`ca`bbbbb``bbbbbbb",
"bbbbbbbb`bbbbb`aa`bbbbb`c`bbbbbb",
"bbbbbbb``bb`bb`aa`bbb`b`c`bbbbbb",
"bbbbbbb``bb`bbb`a`bbb`b`c`bbbbbb",
"bbbbbb`c`bb``bb`a`bb`c``cc`bbbbb",
"bbbbbb`c`bbb`bb`a`bb`c``cc`bbbbb",
"bbbbbb`c`bbb``b``bbbcc``cc`bbbbb",
"bbbbbb`c`bbb``bb`bb``c``cc`bbbbb",
"bbbbbb`a`bbb``bb`bb``cc`aca`bbbb",
"bbbbbb`c`bb`cc`bbb`c`aa`cca`bbbb",
"bbbbbb`a`bb`cc`bbb`a`ccacac`bbbb",
"bbbbbb`c`bb`cca`bb`c`aacaca`bbbb",
"bbbb`b`a`b`caac`b`ca`acaaac`bbbb",
"bbbb`b``bb``caa`b`ac``acaaa`bbbb",
"bbbb``a`bb``aac`b`aac`aaca`bbbbb",
"bbbbb`a`bb``aaa``cacac`aaa`bbbbb",
"bbbbb`a`bb`a`aa``acaaaa`aa`bbbbb",
"bbbbb``bbb`c`aa``aacacaca`bbbbbb",
"bbbbb``bbb`a`aa``acacaaaa`bbbbbb",
"bbbbbb```b`c``a``aaaacaa`bbbbbbb",
"bbbbbb`aa``aa`a``aaaaaaa`bbbbbbb",
"bbbbbb`aaaaca`a``aaaaaa`bbbbbbbb",
"bbbbbbb`aaaaaa```aaaaa`bbbbbbbbb",
"bbbbbbbb``aaaaa`b`aaa`bbbbbbbbbb",
"bbbbbbbbbb`aaaa`bb`aa`bbbbbbbbbb",
"bbbbbbbbbbb``aa`bb`a`bbbbbbbbbbb",
"bbbbbbbbbbbb````bbb`bbbbbbbbbbbb"
};
