#!/bin/sh -
#
#   This uses the pbmplus package to convert any format to xbm
#
for i in "$@" ; do
  if [ -f $i ]; then
    echo "converting \"$i\""
    anytopnm $i | pbmtoxbm |
       sed 's/static  *char/static unsigned char/;
            s/noname\([[_]\)/'"$name"'\1/' ;;

  fi
done
