#!/bin/sh
#
# face2xbm
#   convert an mail face back into a normal xbm file
#
#  Anthony Thyssen         10 Jan 1994       anthony@cit.gu.edu.au
#
(
echo '/* Format_version=1, Width=48, Height=48, Depth=1, Valid_bits_per_item=16'
echo ' */'
uncompface 
) | icontopbm | pbmtoxbm |
       sed 's/static  *char/static unsigned char/;
            s/noname\([[_]\)/'"$name"'\1/' 

