#!/bin/sh -
#
#   This uses the pbmplus package to convert ilbm format to gif
#
for i in "$@" ; do
  if [ -f $i ]; then
    echo "converting \"$i\""
    j=`basename $i .ilbm`
    ilbmtoppm $i | ppmquant 255 | ppmtogif > $j.gif || rm $j.gif
  fi
done
