#!/bin/sh -
#
#   This uses the pbmplus package to convert tiff images to gif
#
for i in "$@" ; do
  if [ -f $i ]; then
    echo "converting \"$i\""
    j=`basename $i .tif`
    j=`basename $j .tiff`
    tifftopnm $i | ppmquant 255 | ppmtogif > $j.gif || rm $j.gif
  fi
done
